### PR TITLE
updates

### PR DESCRIPTION
**Pull request by JT122406**
yeah

### CODE REVIEW

**Comment by Simonsator** [comment]
Is there any benefit in updating the dependencies? As far as I can see no bugs were fixed since jedis 4.1.0 which have any impact to this api.

**Comment by Simonsator** [comment]
Did you test if the plugin still works correctly with the updated libraries?

**Comment by JT122406** [comment]
> Did you test if the plugin still works correctly with the updated libraries?

I will test when I get home on Saturday

**Review by Simonsator — CHANGES_REQUESTED** [review]
We should keep using +. Concat is more prone to npe and less people know what concat does compared to + (keep the code simple)

**Comment by JT122406** [comment]
> We should keep using +. Concat is more prone to npe and less people know what concat does compared to + (keep the code simple)

.concat is faster and more efficient

**Comment by Simonsator** [comment]
+ compiles to concat with NPE checks in byte code. The only reason why it is faster is that it does no null checks. If only a a few strings are concated (3 in this case), the performance impact is absolutely negotiable.

In this case it is much more important for the code to be easily readable.

**Comment by Simonsator** [comment]
Ok I googled it and in fact + is faster than concat.  https://redfin.engineering/java-string-concatenation-which-way-is-best-8f590a7d22a8

**Comment by JT122406** [comment]
hmm different than what I saw but I will push it back

**Pull request merged**
